### Intrisic NumPy array creation

In [1]:
import numpy as np

In [2]:
integers_array=np.arange(10)
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
integers_second_array=np.arange(100,130)
integers_second_array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [4]:
integers_third_array=np.arange(100,151,2)
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [5]:
first_floats_arr=np.linspace(10,20)
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [6]:
second_floats_arr=np.linspace(10,20,5)
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [7]:
first_rand_arr=np.random.rand(10)
first_rand_arr

array([0.71260704, 0.39256516, 0.46726988, 0.58597865, 0.76926131,
       0.47810476, 0.83048169, 0.95593212, 0.41926085, 0.85799609])

In [8]:
second_rand_arr=np.random.rand(4,4)
second_rand_arr

array([[0.46697392, 0.71251143, 0.64890587, 0.43792779],
       [0.79516025, 0.1888439 , 0.04296639, 0.210475  ],
       [0.27597024, 0.96000445, 0.32202358, 0.18595349],
       [0.33870221, 0.89603373, 0.07431204, 0.79535699]])

In [9]:
third_rand_arr=np.random.randint(0,100,20)
third_rand_arr

array([93, 97, 30,  5, 49, 44, 83, 14, 61, 54, 68, 96, 60, 26, 63, 44, 18,
       61, 93,  2])