### Array types and conversions between types

In [2]:
import numpy as np

In [3]:
integers=np.array([10,20,30,40,50])

In [4]:
integers

array([10, 20, 30, 40, 50])

In [5]:
integers[0]

10

In [6]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [7]:
integers[0]=21.5
integers

array([21, 20, 30, 40, 50])

In [8]:
integers.dtype

dtype('int64')

In [9]:
smallerIntegers=np.array(integers,dtype=np.int8)

In [11]:
smallerIntegers

array([21, 20, 30, 40, 50], dtype=int8)

In [12]:
integers.nbytes

40

In [13]:
smallerIntegers.nbytes

5

In [14]:
overflow = np.array([127,128,129], dtype = np.int8)
overflow

array([ 127, -128, -127], dtype=int8)

In [15]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])

In [16]:
floats

array([1.2, 2.3, 3.4, 5.1, 8.3])

In [17]:
floats.dtype

dtype('float64')