### Creating arrays from Lists and other Python structures

In [1]:
import numpy as np

In [2]:
first_list=[1,2,3,4,5,6,7,8,9,10]

In [3]:
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [4]:
first_array=np.array(first_list)

In [5]:
first_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
second_list=[1,2,3,-1.23,50,128000.56,4.56]

In [7]:
second_array=np.array(second_list)

In [8]:
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [9]:
second_array.dtype

dtype('float64')

In [10]:
third_list=['Ann',111111,'Peter',111112,'Susan',111113,'John',111114]


In [11]:
third_array=np.array(third_list)

In [12]:
third_array

array(['Ann', '111111', 'Peter', '111112', 'Susan', '111113', 'John',
       '111114'], dtype='<U21')

In [13]:
first_tuple=(5, 10, 15, 20, 25, 30)


In [14]:
array_from_tuple=np.array(first_tuple)

In [15]:
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [16]:
array_from_tuple.dtype

dtype('int64')

In [17]:
multi_dim_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]] 

In [18]:
arr_from_multi_dim_list=np.array(multi_dim_list)

In [19]:
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])