### Aggregate functions

In [1]:
import numpy as np

In [2]:
first_arr=np.arange(10,110,10)
first_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [3]:
second_arr=np.arange(10,100,10).reshape(3,3)
second_arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [4]:
third_arr=np.arange(10,110,10).reshape(2,5)
third_arr

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [5]:
first_arr.sum()

550

In [6]:
second_arr.sum()

450

In [7]:
third_arr.sum()

550

In [8]:
second_arr.sum(axis=0)

array([120, 150, 180])

In [9]:
second_arr.sum(axis=1)

array([ 60, 150, 240])

In [10]:
first_arr.prod()

36288000000000000

In [11]:
second_arr.prod()

362880000000000

In [12]:
third_arr.prod()

36288000000000000

In [13]:
third_arr.prod(axis=0)

array([ 600, 1400, 2400, 3600, 5000])

In [15]:
np.average(first_arr)

55.0

In [16]:
np.average(second_arr)

50.0

In [17]:
np.average(third_arr)

55.0

In [18]:
np.min(first_arr)

10

In [20]:
np.max(first_arr)

100

In [21]:
np.mean(first_arr)

55.0

In [22]:
np.std(first_arr)

28.722813232690143