### How to get unique items and counts

In [1]:
import numpy as np

In [2]:
first_arr=np.array([1,2,3,4,5,6,1,2,7,2,1,10,7,8])

In [3]:
np.unique(first_arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10])

In [4]:
second_arr=np.array([[1, 1, 2,1] ,[ 3, 1, 2,1] , [1, 1, 2, 1], [ 7, 1, 1, 1]])
second_arr

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [1, 1, 2, 1],
       [7, 1, 1, 1]])

In [5]:
np.unique(second_arr)

array([1, 2, 3, 7])

In [6]:
np.unique(second_arr,axis=0)

array([[1, 1, 2, 1],
       [3, 1, 2, 1],
       [7, 1, 1, 1]])

In [7]:
np.unique(second_arr,axis=1)

array([[1, 1, 2],
       [1, 3, 2],
       [1, 1, 2],
       [1, 7, 1]])

In [8]:
np.unique(first_arr,return_index= True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8, 10]),
 array([ 0,  1,  2,  3,  4,  5,  8, 13, 11]))

In [9]:
np.unique(second_arr,return_counts=True)

(array([1, 2, 3, 7]), array([11,  3,  1,  1]))