### Broadcasting

In [1]:
import numpy as np

In [2]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
b=np.arange(1,4)
b

array([1, 2, 3])

In [4]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [5]:
c=np.arange(1,3)
c

array([1, 2])

In [6]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [7]:
d=np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [8]:
e=np.arange(4)
e

array([0, 1, 2, 3])

In [9]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])