## Decomposition

In [2]:
import numpy as np

In [5]:
first_matrix=np.matrix([[4,8],[10,14]])
print("Matrix:\n",first_matrix)

Matrix:
 [[ 4  8]
 [10 14]]


In [6]:
eigenvalues, eigenvectors = np.linalg.eig(first_matrix)
print("Eigenvalues:", eigenvalues) 
print("Eigenvectors:", eigenvectors) 

Eigenvalues: [-1.24695077 19.24695077]
Eigenvectors: [[-0.83619408 -0.46462222]
 [ 0.54843365 -0.885509  ]]


In [7]:
eigenvalues= np.linalg.eigvals(first_matrix)
print("Eigenvalues:", eigenvalues) 

Eigenvalues: [-1.24695077 19.24695077]


In [9]:
A = np.mat("3 1 4;1 5 9;2 6 5")
print("A\n", A)

U, Sigma, V = np.linalg.svd(A, full_matrices=False)

print("U: ",U)
print("Sigma : ",Sigma)
print("V : ", V)


A
 [[3 1 4]
 [1 5 9]
 [2 6 5]]
U:  [[-0.32463251  0.79898436  0.50619929]
 [-0.75307473  0.1054674  -0.64942672]
 [-0.57226932 -0.59203093  0.56745679]]
Sigma :  [13.58235799  2.84547726  2.32869289]
V :  [[-0.21141476 -0.55392606 -0.80527617]
 [ 0.46331722 -0.78224635  0.41644663]
 [ 0.86060499  0.28505536 -0.42202191]]


In [10]:
print("Product\n", U * np.diag(Sigma) * V)

Product
 [[3. 1. 4.]
 [1. 5. 9.]
 [2. 6. 5.]]


# M=Q*R

In [12]:
A

matrix([[3, 1, 4],
        [1, 5, 9],
        [2, 6, 5]])

In [15]:
b = np.array([1,2,3]).reshape(3,1) 
q, r = np.linalg.qr(A) 
x = np.dot(np.linalg.inv(r), np.dot(q.T, b)) 
x 

matrix([[ 0.26666667],
        [ 0.46666667],
        [-0.06666667]])

In [16]:
np.linalg.solve(A,b)

array([[ 0.26666667],
       [ 0.46666667],
       [-0.06666667]])