### Copies and views

In [1]:
import numpy as np

In [2]:
students_ids_number=np.array([1111,1212,1313,1414,1515,1616,1717,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [3]:
students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

id of students_ids_number 140313891242320
id of students_ids_number_reg 140313891242320


In [4]:
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


In [5]:
students_ids_number_cp=students_ids_number.copy()

In [6]:
print(students_ids_number_cp)

[1111 2222 1313 1414 1515 1616 1717 1818]


In [7]:
print(students_ids_number_cp==students_ids_number)

[ True  True  True  True  True  True  True  True]


In [8]:
print ("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_cp",id(students_ids_number_cp))

id of students_ids_number 140313891242320
id of students_ids_number_cp 140313896668112


In [13]:
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


In [14]:
students_ids_number_v=students_ids_number.view()

In [15]:
students_ids_number_v[0]=2000
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [17]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]
