### Joining and splitting ararys

In [1]:
import numpy as np

In [2]:
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print("first_arr",first_arr)
print("second_arr",second_arr)

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


In [4]:
con_arr=np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [6]:
third_2darr=np.array([[1,2,3,4,5], [6,7,8,9,10]])
third_2darr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
fourth_2darr=np.array([[11,12,13,14,15], [16,17,18,19,20]])
fourth_2darr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [9]:
con2d_arr = np.concatenate((third_2darr,fourth_2darr),axis=1)
con2d_arr

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [10]:
st_arr = np.stack((first_arr,second_arr))
st_arr 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [11]:
hst_arr=np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
vst_arr=np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [13]:
fifth_arr=np.arange(1,13)
fifth_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
sp_arr=np.array_split(fifth_arr,4)
sp_arr

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]), array([10, 11, 12])]

In [15]:
print(sp_arr[1])

[4 5 6]


In [17]:
sp_arr=np.array_split(fifth_arr,8)
sp_arr

[array([1, 2]),
 array([3, 4]),
 array([5, 6]),
 array([7, 8]),
 array([9]),
 array([10]),
 array([11]),
 array([12])]

In [21]:
np.hsplit(third_2darr,5)


[array([[1],
        [6]]),
 array([[2],
        [7]]),
 array([[3],
        [8]]),
 array([[4],
        [9]]),
 array([[ 5],
        [10]])]

In [ ]:
03_06

In [20]:
vs_arr=np.vsplit(third_2darr,2)
vs_arr

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]])]