## Introducing strides

In [3]:
import numpy as np

In [4]:
numbers = np.arange(10, dtype = np.int8)
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8)

In [5]:
numbers.strides

(1,)

In [6]:
numbers.shape = 2,5
numbers

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int8)

In [7]:
numbers.strides

(5, 1)

In [8]:
first_array = np.zeros((100000,)) 
first_array

array([0., 0., 0., ..., 0., 0., 0.])

In [9]:
second_array = np.zeros((100000 * 100, ))[::100] 
second_array 

array([0., 0., 0., ..., 0., 0., 0.])

In [10]:
first_array.shape

(100000,)

In [11]:
second_array.shape

(100000,)

In [12]:
first_array.strides

(8,)

In [13]:
second_array.strides

(800,)

In [14]:
%timeit first_array.sum()

27.7 µs ± 2.67 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [15]:
%timeit second_array.sum()

480 µs ± 23.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
