### Adding, removing and sorting elements

In [1]:
import numpy as np

In [2]:
first_arr=np.array([1, 2, 3, 5])
first_arr

array([1, 2, 3, 5])

In [3]:
new_first_arr=np.insert(first_arr,3,4)
new_first_arr

array([1, 2, 3, 4, 5])

In [4]:
second_arr=np.array([1,2,3,4])
second_arr

array([1, 2, 3, 4])

In [5]:
new_second_arr=np.append(second_arr,5)
new_second_arr

array([1, 2, 3, 4, 5])

In [6]:
third_arr=np.array([1,2,3,4,5])
third_arr

array([1, 2, 3, 4, 5])

In [7]:
del_arr=np.delete(third_arr,4)
del_arr

array([1, 2, 3, 4])

In [8]:
integers_arr=np.random.randint(0,20,20)
integers_arr

array([14, 18,  1,  6, 17,  9,  3,  9,  0, 14, 10, 15, 13, 11, 10, 13, 11,
       12, 18, 15])

In [9]:
print(np.sort(integers_arr))

[ 0  1  3  6  9  9 10 10 11 11 12 13 13 14 14 15 15 17 18 18]


In [10]:
integers_2dim_arr=np.array([[3, 2, 5,7, 4], [5, 0, 8,3, 1]])
integers_2dim_arr

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [11]:
print(np.sort(integers_2dim_arr))

[[2 3 4 5 7]
 [0 1 3 5 8]]


In [12]:
colors=np.array(['orange','green','yellow','white','black','pink','blue','red'])
colors

array(['orange', 'green', 'yellow', 'white', 'black', 'pink', 'blue',
       'red'], dtype='<U6')

In [13]:
print(np.sort(colors))

['black' 'blue' 'green' 'orange' 'pink' 'red' 'white' 'yellow']
