# Array types and conversions.

In [1]:
import numpy as np # import numpy library as np

In [8]:
integars = np.array([13, 22, 36, 42, 59])
integars

array([13, 22, 36, 42, 59])

In [9]:
integars.dtype

dtype('int32')

In [12]:
smallerIntegars = np.array(integars, dtype=np.int8)
smallerIntegars.dtype

dtype('int8')

In [13]:
integars.itemsize   

4

In [14]:
integars.nbytes

20

In [16]:
floats=np.array([1.2,2.3,3.4,5.1,8.3])  
floats

array([1.2, 2.3, 3.4, 5.1, 8.3])

In [17]:
floats.dtype    # float64

dtype('float64')

In [18]:
nums = np.array([[1,2,3,9], 
                 [4,5,6,7]])    # 2 rows, 4 columns
nums

array([[1, 2, 3, 9],
       [4, 5, 6, 7]])

In [20]:
nums[1,2]   # 2nd row, 3rd column

6

In [21]:
nums.ndim  # number of dimensions

2

In [27]:
multi_arr = np.array([[[1,2,3,9],[4,5,6,7]],[[1,3,8,6],[3,9,2,1]]])  # 2x2x4 array
multi_arr 

array([[[1, 2, 3, 9],
        [4, 5, 6, 7]],

       [[1, 3, 8, 6],
        [3, 9, 2, 1]]])

In [28]:
multi_arr[1,0,3] # 2nd array, 1st row, 4th column

6

## Creating arrays with Python Data Structures

####                                                        Using List

In [30]:
first_list = [1,2,3,4,5]
first_list

[1, 2, 3, 4, 5]

In [31]:
first_array = np.array(first_list)
first_array

array([1, 2, 3, 4, 5])

In [32]:
second_list=[1,2,3,-1.23,50,128000.56,4.56]
second_list

[1, 2, 3, -1.23, 50, 128000.56, 4.56]

In [33]:
second_array = np.array(second_list)
second_array

array([ 1.0000000e+00,  2.0000000e+00,  3.0000000e+00, -1.2300000e+00,
        5.0000000e+01,  1.2800056e+05,  4.5600000e+00])

In [34]:
third_list=['Nimra',879,'Taaha',917,'Susan',1098,'Haroon',907]
third_list

['Nimra', 879, 'Taaha', 917, 'Susan', 1098, 'Haroon', 907]

In [35]:
third_array = np.array(third_list)
third_array

array(['Nimra', '879', 'Taaha', '917', 'Susan', '1098', 'Haroon', '907'],
      dtype='<U11')

####                                                        Using Tuple

In [37]:
first_tuple=(5, 10, 15, 20, 25, 30)
first_tuple

(5, 10, 15, 20, 25, 30)

In [39]:
array_from_tuple=np.array(first_tuple)
array_from_tuple

array([ 5, 10, 15, 20, 25, 30])

In [40]:
array_from_tuple.dtype

dtype('int32')

In [41]:
multi_dim_list=[[[0,1,2], [3,4,5]], [[6,7,8],[9,10,11]]] 
multi_dim_list

[[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]]

In [42]:
arr_from_multi_dim_list=np.array(multi_dim_list)
arr_from_multi_dim_list

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

## Intrinsic Array Creation

In [43]:
integers_array=np.arange(10) # 0 to 9
integers_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
integers_second_array=np.arange(50,150) # 50 to 149
integers_second_array

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101,
       102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127,
       128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
       141, 142, 143, 144, 145, 146, 147, 148, 149])

In [45]:
integers_third_array=np.arange(100,150,2) # 100 to 150, step 2
integers_third_array

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148])

In [46]:
first_floats_arr=np.linspace(10,20) # 50 numbers from 10 to 20
first_floats_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [47]:
second_floats_arr=np.linspace(10,20,5) # 5 numbers from 10 to 20
second_floats_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [49]:
first_rand_arr=np.random.rand(15) # 15 random numbers between 0 and 1
first_rand_arr

array([0.39869874, 0.87867838, 0.38767364, 0.7489363 , 0.84944247,
       0.36063754, 0.54991995, 0.26792352, 0.0912705 , 0.40016661,
       0.60611324, 0.67165349, 0.37121543, 0.29938729, 0.76258742])

In [50]:
second_rand_arr=np.random.rand(4,4) # 4x4 array of random numbers between 0 and 1
second_rand_arr

array([[0.84091415, 0.11902358, 0.69624748, 0.58701114],
       [0.54142641, 0.44071473, 0.16691221, 0.08580194],
       [0.38361485, 0.44317394, 0.13548462, 0.57068616],
       [0.38209158, 0.46812901, 0.64875342, 0.45936081]])

In [51]:
third_rand_arr=np.random.randint(0,100,30) # 30 random integers between 0 and 100 
third_rand_arr

array([25, 87, 88, 58, 89, 14, 20, 43,  1, 46, 88, 44, 89, 78, 49, 42, 77,
       17, 36, 69, 64, 70, 79, 46, 90, 88, 15,  1, 47, 74])

In [56]:
forth_rand_arr=np.random.randint(0,30,size=(4,4)) # 4x4 array with random integers between 0 and 30
forth_rand_arr

array([[ 0, 16, 11, 14],
       [ 0, 22, 26,  3],
       [ 4,  8,  1, 25],
       [ 1, 15, 19,  6]])

## Constant Valued Array Creation

In [57]:
first_z_array=np.zeros(10) # 10 zeros
first_z_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [60]:
second_z_array=np.zeros((3,6)) # 3x6 array of zeros
second_z_array

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [61]:
first_ones_array=np.ones(6) # 6 ones
first_ones_array

array([1., 1., 1., 1., 1., 1.])

In [62]:
second_ones_array=np.ones((7,8)) # 7x8 array of ones
second_ones_array

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [63]:
third_ones_array=np.ones((4,5),dtype=int) # 4x5 array of ones
third_ones_array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [66]:
first_fill_array=np.empty(10,dtype=int) # 10 empty integers
first_fill_array.fill(16) # fill with 16
first_fill_array

array([16, 16, 16, 16, 16, 16, 16, 16, 16, 16])

In [67]:
first_full_array=np.full(5,10) # 5 tens
first_full_array

array([10, 10, 10, 10, 10])

In [68]:
second_full_array=np.full((4,5),8) #    4x5 array of eights
second_full_array

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

## Finding size and shape of array

In [70]:
first_arr=np.arange(20) # 0 to 19
first_arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
second_arr=np.linspace((1,2),(10,20),10) # 10 numbers from (1,2) to (10,20)
second_arr

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [72]:
third_arr=np.full((2,2,2),10) # 2x2x2 array of tens
third_arr

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [73]:
np.shape(first_arr) # 1 dimension, 20 elements

(20,)

In [74]:
np.shape(second_arr) # 1 dimension, 10 elements

(10, 2)

In [75]:
np.shape(third_arr) # 3 dimensions, 8 elements

(2, 2, 2)

In [76]:
np.size(first_arr) # 20 elements

20

In [77]:
np.size(second_arr) # 10 elements

20

In [78]:
np.size(third_arr) # 8 elements

8