## Linear algebra capabilities in NumPy

In [1]:
import numpy as np

In [2]:
first_array = np.arange(16).reshape(4,4) 
first_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
first_matrix = np.matrix(first_array)
first_matrix

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [4]:
second_matrix = np.matrix(np.identity(4))
second_matrix

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [5]:
matrix_a=np.random.randint(5,size=(2,3))
matrix_a

array([[1, 2, 0],
       [4, 3, 4]])

In [6]:
matrix_b=np.random.randint(5,size=(3,2))
matrix_b

array([[1, 1],
       [4, 1],
       [0, 3]])

In [7]:
np.matmul(matrix_a,matrix_b)

array([[ 9,  3],
       [16, 19]])

In [8]:
matrix_c=np.matrix("0 1 2;1 0 3;4 -3 8")
matrix_c

matrix([[ 0,  1,  2],
        [ 1,  0,  3],
        [ 4, -3,  8]])

In [9]:
inverse = np.linalg.inv(matrix_c)
inverse

matrix([[-4.5,  7. , -1.5],
        [-2. ,  4. , -1. ],
        [ 1.5, -2. ,  0.5]])

In [10]:
print(matrix_c*inverse)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
A =np.mat("1 -2 1;0 2 -8;-4 5 9")
A

matrix([[ 1, -2,  1],
        [ 0,  2, -8],
        [-4,  5,  9]])

In [12]:
b = np.array([0, 16, -18])
b

array([  0,  16, -18])

In [13]:
x = np.linalg.solve(A, b)
print("Solution", x)

Solution [58. 32.  6.]
