In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
               [4,7,8],
               [5,8,3]])

In [4]:
arr[0:2,0:2]

array([[1, 2],
       [4, 7]])

In [6]:
for i in arr.flat:   #access the array as flat.
    print(i)

1
2
3
4
7
8
5
8
3


In [7]:
a = np.array([[3,2,1,6]
             ,[3,6,5,3]])

In [8]:
b = np.array([[2,6,5,9]
             ,[1,9,3,7]])

In [9]:
np.vstack((a,b))    #Stacks two arrays verticaly

array([[3, 2, 1, 6],
       [3, 6, 5, 3],
       [2, 6, 5, 9],
       [1, 9, 3, 7]])

In [11]:
np.hstack((a,b))    #Stacks two arrays horizontly

array([[3, 2, 1, 6, 2, 6, 5, 9],
       [3, 6, 5, 3, 1, 9, 3, 7]])